# Generated by Django 4.2.5 on 2023-09-27 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='classRaqam',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('gender', models.CharField(default='LAB', max_length=10)),
                ('image', models.ImageField(upload_to='images/students')),
                ('parentName', models.CharField(default='', max_length=255)),
                ('parentNum', models.CharField(default='', max_length=14)),
                ('dateOfBirth', models.DateField()),
                ('registredDate', models.DateField()),
                ('studentClasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classe')),
            ],
        ),
    ]
