# Generated by Django 4.2.5 on 2023-09-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_classe_classraqam_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(default='ذكر', max_length=10),
        ),
    ]
