# Generated by Django 4.2.5 on 2023-09-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_students_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='living',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='motherName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='students',
            name='placeOfBirth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='classRaqam',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/students'),
        ),
    ]
