# Generated by Django 4.2.5 on 2023-11-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_examentring_exammarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examentring',
            name='classe',
        ),
        migrations.AddField(
            model_name='examentring',
            name='classe',
            field=models.ManyToManyField(blank=True, null=True, to='api.classe'),
        ),
    ]
