# Generated by Django 4.2.5 on 2023-12-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_exammarks_classe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-isCurrentAcademicYear']},
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(default='ذكر', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/teachers')),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('dateRegistred', models.DateField(blank=True, null=True)),
                ('educationLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('educatingClasses', models.ManyToManyField(blank=True, null=True, to='api.classe')),
                ('educatingSubjects', models.ManyToManyField(blank=True, null=True, to='api.subject')),
            ],
        ),
    ]
