# Generated by Django 4.2.5 on 2023-12-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_academicyear_options_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
